[tool.poetry]
name = "Temat1"
version = "0.0.1"
description = "Sprzzet dla baz danych"
authors = ["Dlugi, Grajcan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sphinx = "^6.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
